### ISSUE TITLE
升级报错

### ISSUE THREAD

**Issue by molezz** [ahui2016/uglynotes#3]
升级后报错，改用docker试试了

> panic: missing struct tag id or ID field
> 
> goroutine 1 [running]:
> github.com/ahui2016/uglynotes/util.Panic(...)
>         /root/uglynotes/util/util.go:33
> main.init.0()
>         /root/uglynotes/init.go:52 +0x293

**Comment by ahui2016** [comment]
我正在做比较大的底层改动，因此当前版本不可用。几天前有一个可用的版本，请执行  `git checkout 3726d88` 即可回退到一个可用的版本。（以后可以用 `git checkout main` 回到最新状态）

**Comment by Jonnyan404** [comment]
@ahui2016 老版本和新版本兼容么?数据可以直接通过导出和恢复来使用sqlite吗?

**Comment by ahui2016** [comment]
> @ahui2016 老版本和新版本兼容么?数据可以直接通过导出和恢复来使用sqlite吗?

导出老版本的 json 文件，可以导入到新版本，详细说明请看这里: https://github.com/ahui2016/uglynotes/blob/main/Releases.md
